# Generated by Django 6.0.3 on 2026-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#F5F0E8', max_length=20)),
                ('header_color', models.CharField(default='#EDE8DF', max_length=20)),
                ('card_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки доски',
            },
        ),
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#E8E2D8', max_length=20),
        ),
        migrations.AddField(
            model_name='column',
            name='is_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10),
        ),
    ]
