# Generated by Django 6.0.3 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardsettings_column_color_column_is_collapsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsettings',
            name='system_name',
            field=models.CharField(default='Task Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_chief_goal',
            field=models.BooleanField(default=False),
        ),
    ]
