# Generated by Django 6.0.3 on 2026-04-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardsettings_system_name_task_is_chief_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardsettings',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='boardsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_angle',
            field=models.IntegerField(default=135),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_color1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_color2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_gradient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_opacity_card',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_opacity_column',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='boardsettings',
            name='bg_opacity_header',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chief', 'Главный специалист'), ('lead', 'Ведущий специалист'), ('specialist', 'Специалист'), ('senior', 'Старший специалист'), ('junior', 'Младший специалист')], default='junior', max_length=20),
        ),
    ]
