# Generated by Django 6.0.3 on 2026-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_boardsettings_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
