# Generated by Django 6.0.3 on 2026-04-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_task_assigned_by_task_assigned_to_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='board.taskcomment'),
        ),
    ]
