# Generated by GitHub Copilot based on model changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_column_board_boardchatmessage_boardmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='board.boardchatmessage'),
        ),
    ]
