# Generated by Django 6.0.3 on 2026-05-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_boardchatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='board.board'),
        ),
    ]
