# Generated by Django 6.0 on 2026-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_notification_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='edit_columns',
            field=models.BooleanField(default=False, help_text='Может редактировать колонки'),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='reorder_columns',
            field=models.BooleanField(default=False, help_text='Может менять порядок колонок'),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='view_all_tasks',
            field=models.BooleanField(default=False, help_text='Может просматривать все задачи на доске'),
        ),
    ]
